services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  order-service:
    build: ./OrderService
    ports:
      - "5001:8080"
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION=redis:6379

  notification-service:
    build: ./NotificationService
    ports:
      - "5002:8080"
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION=redis:6379